#!/bin/bash
#
# Automate some of the conversion from MoinMoin to Markdown

case "$OSTYPE" in
    darwin*)
        SED_EX_REGEX="-E"
        ;;
    *gnu)
        SED_EX_REGEX="-r"
        ;;
esac

dirname="${0%/*}"

sed -i '' $SED_EX_REGEX -f $dirname/moin-to-md.sed "$@"
